# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

min_pt_cloud_dist <- function(mat1, mat2) {
    .Call('_matools_min_pt_cloud_dist', PACKAGE = 'matools', mat1, mat2)
}

transform_pts <- function(pts, tmat) {
    .Call('_matools_transform_pts', PACKAGE = 'matools', pts, tmat)
}

